# Generated by Django 3.0.4 on 2020-03-19 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200318_0902'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppShaderColor',
        ),
    ]
